package sync

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/florianriquelme/sshjesus/internal/domain"
)

func TestWriteSSHIncludeFile_FullServer(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create a server with all fields populated
	server := &domain.Server{
		ID:           "srv-001",
		DisplayName:  "prod-web-01",
		Host:         "192.168.1.100",
		User:         "deploy",
		Port:         2222,
		IdentityFile: "~/.ssh/id_ed25519",
		Proxy:        "bastion.example.com",
	}

	// Write the include file
	err := WriteSSHIncludeFile([]*domain.Server{server}, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(includePath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify header comment
	assert.Contains(t, contentStr, "# Generated by sshjesus - DO NOT EDIT MANUALLY")
	assert.Contains(t, contentStr, "# Source: 1Password")
	assert.Contains(t, contentStr, "# Last sync:")

	// Verify Host block
	assert.Contains(t, contentStr, "Host prod-web-01")
	assert.Contains(t, contentStr, "    HostName 192.168.1.100")
	assert.Contains(t, contentStr, "    User deploy")
	assert.Contains(t, contentStr, "    Port 2222")
	assert.Contains(t, contentStr, "    IdentityFile ~/.ssh/id_ed25519")
	assert.Contains(t, contentStr, "    ProxyJump bastion.example.com")
}

func TestWriteSSHIncludeFile_MinimalServer(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create a minimal server (only required fields + port 22)
	server := &domain.Server{
		ID:          "srv-002",
		DisplayName: "staging-db",
		Host:        "staging.example.com",
		User:        "ubuntu",
		Port:        22, // Default port
	}

	// Write the include file
	err := WriteSSHIncludeFile([]*domain.Server{server}, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(includePath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify basic fields are present
	assert.Contains(t, contentStr, "Host staging-db")
	assert.Contains(t, contentStr, "    HostName staging.example.com")
	assert.Contains(t, contentStr, "    User ubuntu")

	// Verify port 22 is NOT included (SSH default)
	assert.NotContains(t, contentStr, "Port 22")

	// Verify optional fields are NOT included
	assert.NotContains(t, contentStr, "IdentityFile")
	assert.NotContains(t, contentStr, "ProxyJump")
}

func TestWriteSSHIncludeFile_MultipleServers(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create three servers
	servers := []*domain.Server{
		{
			ID:          "srv-001",
			DisplayName: "prod-web",
			Host:        "prod.example.com",
			User:        "deploy",
			Port:        22,
		},
		{
			ID:          "srv-002",
			DisplayName: "staging-api",
			Host:        "staging.example.com",
			User:        "ubuntu",
			Port:        2222,
		},
		{
			ID:          "srv-003",
			DisplayName: "dev-db",
			Host:        "dev.example.com",
			User:        "admin",
			Port:        22,
		},
	}

	// Write the include file
	err := WriteSSHIncludeFile(servers, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(includePath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify all three servers are present
	assert.Contains(t, contentStr, "Host prod-web")
	assert.Contains(t, contentStr, "Host staging-api")
	assert.Contains(t, contentStr, "Host dev-db")

	// Verify blocks are separated by blank lines
	lines := strings.Split(contentStr, "\n")
	blockCount := 0
	for i, line := range lines {
		if strings.HasPrefix(line, "Host ") {
			blockCount++
			// Check if there's a blank line before this block (except the first host)
			if blockCount > 1 && i > 0 {
				assert.Equal(t, "", strings.TrimSpace(lines[i-1]), "Expected blank line before Host block")
			}
		}
	}

	assert.Equal(t, 3, blockCount, "Expected 3 Host blocks")
}

func TestWriteSSHIncludeFile_EmptyServers(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Write with empty server list
	err := WriteSSHIncludeFile([]*domain.Server{}, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(includePath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify header is present
	assert.Contains(t, contentStr, "# Generated by sshjesus")

	// Verify no Host blocks
	assert.NotContains(t, contentStr, "Host ")
}

func TestWriteSSHIncludeFile_Permissions(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create a simple server
	server := &domain.Server{
		ID:          "srv-001",
		DisplayName: "test-server",
		Host:        "test.example.com",
		User:        "testuser",
		Port:        22,
	}

	// Write the include file
	err := WriteSSHIncludeFile([]*domain.Server{server}, includePath)
	require.NoError(t, err)

	// Check file permissions
	fileInfo, err := os.Stat(includePath)
	require.NoError(t, err)

	// Verify permissions are 0600
	assert.Equal(t, os.FileMode(0600), fileInfo.Mode().Perm(), "Expected file permissions to be 0600")
}

func TestEnsureIncludeDirective_NewFile(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	sshConfigPath := filepath.Join(tmpDir, "config")
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Ensure include directive (file doesn't exist yet)
	err := EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify Include directive is present
	assert.Contains(t, contentStr, "# sshjesus 1Password integration")
	assert.Contains(t, contentStr, "Include "+includePath)

	// Verify file was created with correct permissions
	fileInfo, err := os.Stat(sshConfigPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), fileInfo.Mode().Perm())
}

func TestEnsureIncludeDirective_ExistingWithoutInclude(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	sshConfigPath := filepath.Join(tmpDir, "config")
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create existing SSH config
	existingContent := `Host myserver
    HostName example.com
    User admin

Host another
    HostName another.com
    User user
`
	err := os.WriteFile(sshConfigPath, []byte(existingContent), 0600)
	require.NoError(t, err)

	// Ensure include directive
	err = EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify Include directive is prepended
	lines := strings.Split(contentStr, "\n")
	foundIncludeComment := false
	foundInclude := false
	foundExistingContent := false

	for i, line := range lines {
		if strings.Contains(line, "# sshjesus 1Password integration") {
			foundIncludeComment = true
			assert.Less(t, i, 3, "Include comment should be at the top")
		}
		if strings.Contains(line, "Include "+includePath) {
			foundInclude = true
			assert.Less(t, i, 5, "Include directive should be near the top")
		}
		if strings.Contains(line, "Host myserver") {
			foundExistingContent = true
			// Existing content should come after Include
			assert.True(t, foundInclude, "Include should come before existing content")
		}
	}

	assert.True(t, foundIncludeComment, "Include comment not found")
	assert.True(t, foundInclude, "Include directive not found")
	assert.True(t, foundExistingContent, "Existing content not preserved")
}

func TestEnsureIncludeDirective_AlreadyPresent(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	sshConfigPath := filepath.Join(tmpDir, "config")
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create SSH config with Include already present
	existingContent := `# sshjesus 1Password integration
Include ` + includePath + `

Host myserver
    HostName example.com
    User admin
`
	err := os.WriteFile(sshConfigPath, []byte(existingContent), 0600)
	require.NoError(t, err)

	// Ensure include directive (should be no-op)
	err = EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	contentStr := string(content)

	// Verify content is unchanged
	assert.Equal(t, existingContent, contentStr, "Content should be unchanged")
}

func TestEnsureIncludeDirective_Idempotent(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	sshConfigPath := filepath.Join(tmpDir, "config")
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create existing SSH config
	existingContent := `Host myserver
    HostName example.com
    User admin
`
	err := os.WriteFile(sshConfigPath, []byte(existingContent), 0600)
	require.NoError(t, err)

	// Call EnsureIncludeDirective twice
	err = EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read content after first call
	contentAfterFirst, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	// Call again
	err = EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read content after second call
	contentAfterSecond, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	// Verify content is identical after both calls
	assert.Equal(t, string(contentAfterFirst), string(contentAfterSecond), "Multiple calls should be idempotent")

	// Verify Include appears only once
	includeCount := strings.Count(string(contentAfterSecond), "Include "+includePath)
	assert.Equal(t, 1, includeCount, "Include directive should appear exactly once")
}

func TestEnsureIncludeDirective_CaseInsensitive(t *testing.T) {
	// Create temp directory for test
	tmpDir := t.TempDir()
	sshConfigPath := filepath.Join(tmpDir, "config")
	includePath := filepath.Join(tmpDir, "sshjesus_config")

	// Create SSH config with Include in different case
	existingContent := `# sshjesus 1Password integration
include ` + includePath + `

Host myserver
    HostName example.com
    User admin
`
	err := os.WriteFile(sshConfigPath, []byte(existingContent), 0600)
	require.NoError(t, err)

	// Ensure include directive (should be no-op since "include" exists)
	err = EnsureIncludeDirective(sshConfigPath, includePath)
	require.NoError(t, err)

	// Read and verify content
	content, err := os.ReadFile(sshConfigPath)
	require.NoError(t, err)

	// Verify Include was not added again
	includeCount := strings.Count(strings.ToLower(string(content)), "include "+strings.ToLower(includePath))
	assert.Equal(t, 1, includeCount, "Include directive should appear exactly once (case-insensitive)")
}
